;;;; GENERATED by tools/generate-chrome-shader.lisp — do not hand-edit.
;;;; Standard HSV->RGB, via tools/hsv-shader-lib.lisp's shared generator —
;;;; not a private copy of the hexagonal-cone construction. MOD/FLOOR
;;;; avoided in that library — c-mera treats those as Lisp-level special
;;;; forms (CL-homonym names), not GLSL passthroughs; they type-error on a
;;;; live GLSL expression node at shader-build time.
;;;; Regenerate: sbcl --script tools/generate-chrome-shader.lisp

(decl ((in vec2 |fragTexCoord|)))

(decl ((in vec4 |fragColor|)))

(decl ((uniform float hue)))

(decl ((uniform float saturation)))

(decl ((uniform float value)))

(decl ((uniform float alpha)))

(decl ((out vec4 |finalColor|)))

(function main nil -> void (decl ((vec3 color))) (decl ((float h6)))
 (decl ((float f))) (set h6 (* hue 6.0))
 (if (< h6 1.0)
     (progn
      (set f (- h6 0.0))
      (set color
           (vec3 value (* value (- 1.0 (* saturation (- 1.0 f))))
            (* value (- 1.0 saturation)))))
     (if (< h6 2.0)
         (progn
          (set f (- h6 1.0))
          (set color
               (vec3 (* value (- 1.0 (* saturation f))) value
                (* value (- 1.0 saturation)))))
         (if (< h6 3.0)
             (progn
              (set f (- h6 2.0))
              (set color
                   (vec3 (* value (- 1.0 saturation)) value
                    (* value (- 1.0 (* saturation (- 1.0 f)))))))
             (if (< h6 4.0)
                 (progn
                  (set f (- h6 3.0))
                  (set color
                       (vec3 (* value (- 1.0 saturation))
                        (* value (- 1.0 (* saturation f))) value)))
                 (if (< h6 5.0)
                     (progn
                      (set f (- h6 4.0))
                      (set color
                           (vec3 (* value (- 1.0 (* saturation (- 1.0 f))))
                            (* value (- 1.0 saturation)) value)))
                     (progn
                      (set f (- h6 5.0))
                      (set color
                           (vec3 value (* value (- 1.0 saturation))
                            (* value (- 1.0 (* saturation f)))))))))))
 (set |finalColor| (vec4 color alpha)))

