;;;; GENERATED by tools/generate-queens-shader.lisp — do not hand-edit.
;;;; Same tools/hsv-shader-lib.lisp generator as chrome.fs.lisp, called with
;;;; a computed VALUE expression (a TIME-driven pulse when CURSOR=1) instead
;;;; of a plain uniform — the region's hue still comes in as a uniform.
;;;; Regenerate: sbcl --script tools/generate-queens-shader.lisp

(decl ((in vec2 |fragTexCoord|)))

(decl ((in vec4 |fragColor|)))

(decl ((uniform float hue)))

(decl ((uniform int cursor)))

(decl ((uniform float time)))

(decl ((out vec4 |finalColor|)))

(function main nil -> void (decl ((vec3 color))) (decl ((float h6)))
 (decl ((float f))) (decl ((float v))) (decl ((float pulse)))
 (set pulse (+ 0.5 (* 0.5 (sin (* time 6.0)))))
 (if (== cursor 1)
     (set v (+ 0.7 (* 0.3 pulse)))
     (set v 0.82))
 (set h6 (* hue 6.0))
 (if (< h6 1.0)
     (progn
      (set f (- h6 0.0))
      (set color (vec3 v (* v (- 1.0 (* 0.55 (- 1.0 f)))) (* v (- 1.0 0.55)))))
     (if (< h6 2.0)
         (progn
          (set f (- h6 1.0))
          (set color (vec3 (* v (- 1.0 (* 0.55 f))) v (* v (- 1.0 0.55)))))
         (if (< h6 3.0)
             (progn
              (set f (- h6 2.0))
              (set color
                   (vec3 (* v (- 1.0 0.55)) v
                    (* v (- 1.0 (* 0.55 (- 1.0 f)))))))
             (if (< h6 4.0)
                 (progn
                  (set f (- h6 3.0))
                  (set color
                       (vec3 (* v (- 1.0 0.55)) (* v (- 1.0 (* 0.55 f))) v)))
                 (if (< h6 5.0)
                     (progn
                      (set f (- h6 4.0))
                      (set color
                           (vec3 (* v (- 1.0 (* 0.55 (- 1.0 f))))
                            (* v (- 1.0 0.55)) v)))
                     (progn
                      (set f (- h6 5.0))
                      (set color
                           (vec3 v (* v (- 1.0 0.55))
                            (* v (- 1.0 (* 0.55 f)))))))))))
 (set |finalColor| (vec4 color 1.0)))

