;;;; tools/generate-chrome-shader.lisp
;;;;
;;;; Generates src/shaders/chrome.fs.lisp from tools/hsv-shader-lib.lisp's
;;;; shared HSV->RGB generator — a thin consumer, not a second copy of
;;;; the hexagonal-cone construction. hue/saturation/value/alpha here
;;;; are plain uniform references; see generate-queens-cell-shader.lisp
;;;; for a caller that passes computed expressions instead.
;;;;
;;;; Usage: sbcl --script tools/generate-chrome-shader.lisp

(load (merge-pathnames "hsv-shader-lib.lisp" *load-pathname*))

(defparameter *chrome-fs-forms*
  `((decl ((in vec2 |fragTexCoord|)))
    (decl ((in vec4 |fragColor|)))
    (decl ((uniform float hue)))
    (decl ((uniform float saturation)))
    (decl ((uniform float value)))
    (decl ((uniform float alpha)))
    (decl ((out vec4 |finalColor|)))
    (function main () -> void
      (decl ((vec3 color)))
      (decl ((float h6)))
      (decl ((float f)))
      ,@(hsv-color-forms 'hue 'color 'value 'saturation 'h6 'f)
      (set |finalColor| (vec4 color alpha)))))

(with-open-file (out "src/shaders/chrome.fs.lisp" :direction :output
                                                    :if-exists :supersede :if-does-not-exist :create)
  (format out ";;;; GENERATED by tools/generate-chrome-shader.lisp — do not hand-edit.~%")
  (format out ";;;; Standard HSV->RGB, via tools/hsv-shader-lib.lisp's shared generator —~%")
  (format out ";;;; not a private copy of the hexagonal-cone construction. MOD/FLOOR~%")
  (format out ";;;; avoided in that library — c-mera treats those as Lisp-level special~%")
  (format out ";;;; forms (CL-homonym names), not GLSL passthroughs; they type-error on a~%")
  (format out ";;;; live GLSL expression node at shader-build time.~%")
  (format out ";;;; Regenerate: sbcl --script tools/generate-chrome-shader.lisp~%~%")
  (dolist (form *chrome-fs-forms*)
    (let ((*print-case* :downcase))
      (prin1 form out))
    (terpri out)
    (terpri out)))

(format t "~&wrote src/shaders/chrome.fs.lisp~%")
