;;;; tools/generate-queens-shader.lisp
;;;;
;;;; Generates src/games/queens/shaders/cell.fs.lisp from
;;;; tools/hsv-shader-lib.lisp's shared HSV->RGB generator — the same
;;;; generator chrome.fs uses, called with a computed VALUE expression
;;;; instead of a plain uniform: the cursor cell's brightness pulses via
;;;; a sine wave driven by a TIME uniform, a real GPU-side selection-
;;;; glow effect, not a separate DRAW-RECTANGLE-LINES-EX overlay drawn
;;;; on top. This is the concrete proof the shared generator is real
;;;; reusable infrastructure, not chrome-only: two different shaders,
;;;; one hexagonal-cone implementation.
;;;;
;;;; Usage: sbcl --script tools/generate-queens-shader.lisp

(load (merge-pathnames "hsv-shader-lib.lisp" *load-pathname*))

(defparameter *queens-cell-fs-forms*
  `((decl ((in vec2 |fragTexCoord|)))
    (decl ((in vec4 |fragColor|)))
    (decl ((uniform float hue)))
    (decl ((uniform int cursor)))
    (decl ((uniform float time)))
    (decl ((out vec4 |finalColor|)))
    ;; cursor: 0=normal cell, 1=cursor is on this cell (pulsing highlight)
    (function main () -> void
      (decl ((vec3 color)))
      (decl ((float h6)))
      (decl ((float f)))
      (decl ((float v)))
      (decl ((float pulse)))
      (set pulse (+ 0.5 (* 0.5 (sin (* time 6.0)))))
      (if (== cursor 1)
          (set v (+ 0.7 (* 0.3 pulse)))
          (set v 0.82))
      ,@(hsv-color-forms 'hue 'color 'v 0.55 'h6 'f)
      (set |finalColor| (vec4 color 1.0)))))

(with-open-file (out "src/games/queens/shaders/cell.fs.lisp" :direction :output
                                                              :if-exists :supersede :if-does-not-exist :create)
  (format out ";;;; GENERATED by tools/generate-queens-shader.lisp — do not hand-edit.~%")
  (format out ";;;; Same tools/hsv-shader-lib.lisp generator as chrome.fs.lisp, called with~%")
  (format out ";;;; a computed VALUE expression (a TIME-driven pulse when CURSOR=1) instead~%")
  (format out ";;;; of a plain uniform — the region's hue still comes in as a uniform.~%")
  (format out ";;;; Regenerate: sbcl --script tools/generate-queens-shader.lisp~%~%")
  (dolist (form *queens-cell-fs-forms*)
    (let ((*print-case* :downcase))
      (prin1 form out))
    (terpri out)
    (terpri out)))

(format t "~&wrote src/games/queens/shaders/cell.fs.lisp~%")
