;;;; tools/generate-chrome-shader.lisp
;;;;
;;;; The HSV->RGB hexagonal-cone construction has six branches that are
;;;; the same three component-roles (full/min/rising-edge/falling-edge)
;;;; permuted across (r g b). Hand-typing all six (as the original
;;;; chrome.fs.lisp did) means the same three formulas appear ~12 times
;;;; with only their component position changing — real duplication, the
;;;; kind Lisp macros exist to kill. This generates that structure from
;;;; a 6-row permutation table instead, and writes the result as
;;;; src/shaders/chrome.fs.lisp — c-mera's GLSL compiler then processes
;;;; that generated file exactly as before; nothing about the c-mera
;;;; pipeline itself changes.
;;;;
;;;; Usage: sbcl --non-interactive --load tools/generate-chrome-shader.lisp

(defparameter *hsv-sector-roles*
  '((:full :rising :min)
    (:falling :full :min)
    (:min :full :rising)
    (:min :falling :full)
    (:rising :min :full)
    (:full :min :falling))
  "Row I gives the (r g b) component role for hue-sector I. Each role
maps to one of the three chroma formulas via HSV-ROLE-EXPR — this table
IS the hexagonal-cone construction; nothing else needs to encode it.")

(defun hsv-role-expr (role)
  (ecase role
    (:full 'value)
    (:min '(* value (- 1.0 saturation)))
    (:rising '(* value (- 1.0 (* saturation (- 1.0 f)))))
    (:falling '(* value (- 1.0 (* saturation f))))))

(defun hsv-sector-branch (sector-index)
  (destructuring-bind (r g b) (nth sector-index *hsv-sector-roles*)
    `(progn
       (set f (- h6 ,(float sector-index 1.0)))
       (set color (vec3 ,(hsv-role-expr r) ,(hsv-role-expr g) ,(hsv-role-expr b))))))

(defun build-hsv-if-chain (&optional (sector 0))
  (if (= sector 5)
      (hsv-sector-branch 5)
      `(if (< h6 ,(float (1+ sector) 1.0))
           ,(hsv-sector-branch sector)
           ,(build-hsv-if-chain (1+ sector)))))

(defparameter *chrome-fs-forms*
  `((decl ((in vec2 |fragTexCoord|)))
    (decl ((in vec4 |fragColor|)))
    (decl ((uniform float hue)))
    (decl ((uniform float saturation)))
    (decl ((uniform float value)))
    (decl ((uniform float alpha)))
    (decl ((out vec4 |finalColor|)))
    (function main () -> void
      (decl ((vec3 color)))
      (decl ((float h6)))
      (decl ((float f)))
      (set h6 (* hue 6.0))
      ,(build-hsv-if-chain)
      (set |finalColor| (vec4 color alpha)))))

(with-open-file (out "src/shaders/chrome.fs.lisp" :direction :output
                                                    :if-exists :supersede :if-does-not-exist :create)
  (format out ";;;; GENERATED by tools/generate-chrome-shader.lisp — do not hand-edit.~%")
  (format out ";;;; Standard HSV->RGB hexagonal-cone construction, six sectors expanded~%")
  (format out ";;;; from *HSV-SECTOR-ROLES* instead of hand-typed. MOD/FLOOR avoided —~%")
  (format out ";;;; c-mera treats those as Lisp-level special forms (CL-homonym names),~%")
  (format out ";;;; not GLSL passthroughs; they type-error on a live GLSL expression node~%")
  (format out ";;;; at shader-build time. Regenerate: sbcl --script tools/generate-chrome-shader.lisp~%~%")
  (dolist (form *chrome-fs-forms*)
    (let ((*print-case* :downcase))
      (prin1 form out))
    (terpri out)
    (terpri out)))

(format t "~&wrote src/shaders/chrome.fs.lisp~%")
