(in-package :edm-engine/games/queens)


(defparameter +cell-size+ 60.0)
(defparameter +cell-gap+ 4.0)
(defparameter +queen-glyph+ "♛") ; U+265B BLACK CHESS QUEEN — not "Q"/"q"

;;; Cell shader: genuine GPU HSV coloring, generated by the same shared
;;; tools/hsv-shader-lib.lisp generator chrome.fs.lisp uses — this is
;;; the concrete proof that investment is real reusable infrastructure,
;;; not a chrome-only generator. The cursor cell's brightness pulses on
;;; the GPU (TIME-driven sine), a real selection-glow effect the shader
;;; itself expresses, not a DRAW-RECTANGLE-LINES-EX overlay on top.

(defvar *cell-shader* nil)
(defvar *cell-hue-loc* nil)
(defvar *cell-cursor-loc* nil)
(defvar *cell-time-loc* nil)

(defun cell-vertex-shader-path ()
  "Shared with chrome.fs — see PASSTHROUGH.VS.LISP's own docstring for
why this isn't a same-named per-shader-pack .vs file."
  (namestring (asdf:system-relative-pathname :edm-engine "src/shaders/passthrough.vs")))

(defun cell-fragment-shader-path ()
  (namestring (asdf:system-relative-pathname :edm-engine/games/queens "src/games/queens/shaders/cell.fs")))

(defun ensure-cell-shader ()
  (unless *cell-shader*
    (setf *cell-shader* (raylib:load-shader (cell-vertex-shader-path) (cell-fragment-shader-path)))
    (setf *cell-hue-loc* (raylib:get-shader-location *cell-shader* "hue"))
    (setf *cell-cursor-loc* (raylib:get-shader-location *cell-shader* "cursor"))
    (setf *cell-time-loc* (raylib:get-shader-location *cell-shader* "time"))))

(defun draw-cell (x y region-id size cursor-p elapsed)
  (ensure-cell-shader)
  (raylib:begin-shader-mode *cell-shader*)
  (edm-engine:set-shader-float *cell-shader* *cell-hue-loc* (/ (float region-id 1.0) size))
  (edm-engine:set-shader-int *cell-shader* *cell-cursor-loc* (if cursor-p 1 0))
  (edm-engine:set-shader-float *cell-shader* *cell-time-loc* elapsed)
  (raylib:draw-rectangle (round x) (round y) (round +cell-size+) (round +cell-size+) :white)
  (raylib:end-shader-mode))

(defun queens-grid-origin (window-width window-height size)
  (let ((total (+ (* size +cell-size+) (* (1- size) +cell-gap+))))
    (values (/ (- window-width total) 2.0) (/ (- window-height total) 2.0))))

(defun draw-cell-glyph (game x y row col conflicts)
  "The 'miss-placed X' and queen states both need real visual feedback:
a mark shows a plain X, a queen shows the crown glyph — tinted red if
QUEENS-CONFLICTS flags it, so a conflicting placement is genuinely
visible, not just silently non-advancing."
  (ecase (cell-state game row col)
    (:empty nil)
    (:marked
     (let* ((label "X") (font-size 26) (tw (raylib:measure-text label font-size)))
       (raylib:draw-text label (round (+ x (/ (- +cell-size+ tw) 2.0)))
                          (round (+ y (/ (- +cell-size+ font-size) 2.0)))
                          font-size (edm-engine:rgb-color (edm-engine:theme-color :muted)))))
    (:queen
     (let* ((font-size 30)
            (tw (edm-engine:glyph-text-width +queen-glyph+ font-size))
            (conflicted (member (cons row col) conflicts :test #'equal)))
       (edm-engine:draw-glyph-text +queen-glyph+ (round (+ x (/ (- +cell-size+ tw) 2.0)))
                          (round (+ y (/ (- +cell-size+ font-size) 2.0)))
                          font-size (if conflicted (edm-engine:rgb-color edm-engine:+color-red+) :black))))))

(defun draw-queens-board (game window-width window-height)
  (let* ((board (queens-game-board game))
         (size (queens-board-size board))
         (elapsed (raylib:get-time))
         (conflicts (queens-conflicts game)))
    (multiple-value-bind (ox oy) (queens-grid-origin window-width window-height size)
      (dotimes (row size)
        (dotimes (col size)
          (let ((x (+ ox (* col (+ +cell-size+ +cell-gap+))))
                (y (+ oy (* row (+ +cell-size+ +cell-gap+))))
                (cursor-p (and (= row (queens-game-cursor-row game)) (= col (queens-game-cursor-col game)))))
            (draw-cell x y (region-at board row col) size cursor-p elapsed)
            (draw-cell-glyph game x y row col conflicts))))
      (raylib:draw-text
       (format nil "Level ~D/~D   Score ~D~A" (queens-game-level game) +queens-level-count+
               (queens-game-score game) (if conflicts "   (conflict!)" ""))
       (round ox) (round (- oy 36)) 22 :white))))

(defmethod edm-engine:game-title ((game queens-game))
  "Queens")

(defvar *theme-sound* nil)

(defun ensure-theme-playing ()
  "PATTERN-SOUND is cached (CACHED-OR-COMPUTE, in playback.lisp) — this
gets the same Sound object every call, not a fresh render each time.
Polling IS-SOUND-PLAYING and re-triggering PLAY-SOUND when it's false
is how looping works without raylib's separate Music-streaming API,
which this engine doesn't use anywhere else."
  (unless *theme-sound*
    (setf *theme-sound*
          (edm-engine/audio:pattern-sound (queens-theme-pattern) +queens-theme-row-duration+
                                           :amplitude 0.3)))
  (unless (raylib:is-sound-playing *theme-sound*)
    (raylib:play-sound *theme-sound*)))

(defmethod edm-engine:game-update ((game queens-game))
  (ensure-theme-playing)
  (let ((before-row (queens-game-cursor-row game))
        (before-col (queens-game-cursor-col game))
        (before-level (queens-game-level game)))
    (when (raylib:is-key-pressed :key-up) (move-cursor game -1 0))
    (when (raylib:is-key-pressed :key-down) (move-cursor game 1 0))
    (when (raylib:is-key-pressed :key-left) (move-cursor game 0 -1))
    (when (raylib:is-key-pressed :key-right) (move-cursor game 0 1))
    (when (or (/= before-row (queens-game-cursor-row game)) (/= before-col (queens-game-cursor-col game)))
      (edm-engine/audio:play-tone :sine 500.0 0.03))
    (when (raylib:is-key-pressed :key-enter)
      (let ((state-before (cell-state game (queens-game-cursor-row game) (queens-game-cursor-col game))))
        (cycle-cell-at-cursor game)
        (cond
          ((> (queens-game-level game) before-level)
           (edm-engine/audio:play-tone :sine 1000.0 0.3))
          ((eq state-before :empty) (edm-engine/audio:play-tone :square 400.0 0.04))   ; -> marked
          ((eq state-before :marked) (edm-engine/audio:play-tone :square 700.0 0.05))  ; -> queen
          (t (edm-engine/audio:play-tone :square 250.0 0.05)))))))                     ; -> cleared

(defmethod edm-engine:game-render ((game queens-game) window-width window-height)
  (draw-queens-board game window-width window-height))

(defmethod edm-engine:game-stop-audio ((game queens-game))
  (declare (ignore game))
  (when *theme-sound* (raylib:stop-sound *theme-sound*)))

;; No :RESTORE-FN yet — Queens doesn't support save/load resume in this
;; first playable pass. An honest scope cut, not an oversight: the
;; slot system's contract (GAME-ENTRY-RESTORE-FN nil = "this table
;; doesn't support save/load") already handles it cleanly.
(edm-engine:register-game "Queens" (lambda () (make-queens-game)))
