(in-package :edm-engine/games/queens)

;; #59's audio piece — was five direct, inline PLAY-TONE calls in
;; GAME-UPDATE, now declared as data.
(edm-engine/audio:defaudio-cues :queens
  (:cursor-moved :sine 500.0 0.03)
  (:level-advanced :sine 1000.0 0.3)
  (:cell-marked :square 400.0 0.04)
  (:queen-placed :square 700.0 0.05)
  (:cell-cleared :square 250.0 0.05))

(defparameter +cell-size+ 60.0)
(defparameter +cell-gap+ 4.0)
(defparameter +queen-glyph+ "♛") ; U+265B BLACK CHESS QUEEN — not "Q"/"q"

;;; Cell shader: genuine GPU HSV coloring, generated by the same shared
;;; tools/hsv-shader-lib.lisp generator chrome.fs.lisp uses — this is
;;; the concrete proof that investment is real reusable infrastructure,
;;; not a chrome-only generator. The cursor cell's brightness pulses on
;;; the GPU (TIME-driven sine), a real selection-glow effect the shader
;;; itself expresses, not a DRAW-RECTANGLE-LINES-EX overlay on top.

(defvar *cell-shader* nil)
(defvar *cell-hue-loc* nil)
(defvar *cell-cursor-loc* nil)
(defvar *cell-time-loc* nil)

;; #24's fix — embedded at compile time. PASSTHROUGH.VS's own source is
;; already embedded once in RENDER.LISP (+CHROME-VERTEX-SHADER-SOURCE+);
;; re-embedding it here rather than referencing that variable directly
;; keeps this file's own system (EDM-ENGINE/GAMES/QUEENS/RENDER) from
;; needing a cross-system reference for one shared string — the actual
;; DejaVuSans-style "one shared file" reasoning is unchanged, just
;; embedded independently in each of its two consumers rather than
;; loaded from one shared path both read at runtime.
(defparameter +cell-vertex-shader-source+
  (edm-engine/asset-embed:embedFileString "src/shaders/passthrough.vs"))
(defparameter +cell-fragment-shader-source+
  (edm-engine/asset-embed:embedFileString "src/shaders/queens/cell.fs"
                                           :system :edm-engine/games/queens))

(defun ensure-cell-shader ()
  (unless *cell-shader*
    (setf *cell-shader* (raylib:load-shader-from-memory +cell-vertex-shader-source+ +cell-fragment-shader-source+))
    (setf *cell-hue-loc* (raylib:get-shader-location *cell-shader* "hue"))
    (setf *cell-cursor-loc* (raylib:get-shader-location *cell-shader* "cursor"))
    (setf *cell-time-loc* (raylib:get-shader-location *cell-shader* "time"))))

(defun draw-cell (x y region-id size cursor-p elapsed)
  (ecase edm-engine:*render-mode*
    (:gpu
     (ensure-cell-shader)
     (raylib:begin-shader-mode *cell-shader*)
     (edm-engine:set-shader-float *cell-shader* *cell-hue-loc* (/ (float region-id 1.0) size))
     (edm-engine:set-shader-int *cell-shader* *cell-cursor-loc* (if cursor-p 1 0))
     (edm-engine:set-shader-float *cell-shader* *cell-time-loc* elapsed)
     (raylib:draw-rectangle (round x) (round y) (round +cell-size+) (round +cell-size+) :white)
     (raylib:end-shader-mode))
    (:cpu
     (let ((line-color (if (eq edm-engine:*theme-direction* :dark) :white :black)))
       (raylib:draw-rectangle-lines-ex
        (raylib:make-rectangle :x (float x 1.0) :y (float y 1.0) :width (float +cell-size+ 1.0) :height (float +cell-size+ 1.0))
        (if cursor-p 2.5 1.0) line-color)
       (raylib:draw-text (format nil "~D" region-id) (round (+ x 4)) (round (+ y 4)) 12 line-color)))))

;; #36's DEFLAYOUT retrofit — was hand-rolled 2D-centering math
;; duplicating what Wordle independently reimplements too (this
;; session's own earlier CENTERED-GRID-POSITIONS retrofit); now
;; declared as data via DEFLAYOUT itself, not a bare function body
;; calling the primitive directly. +CELL-GAP+'s own value (4.0)
;; genuinely IS +SPACE-1+ (4) — checked directly, not assumed — used
;; explicitly here rather than the untyped float literal it's always
;; equaled.
(edm-engine:deflayout queens-cell-position (row col window-width window-height size)
  (:grid :rows size :cols size :item-w (round +cell-size+) :item-h (round +cell-size+)
         :gap-x edm-engine:+space-1+ :gap-y edm-engine:+space-1+
         :container-w window-width :container-h window-height
         :row-index row :col-index col))

(defun queens-grid-origin (window-width window-height size)
  "Only the origin (row 0, col 0) is needed here, not the full per-cell
lookup — DRAW-QUEENS-BOARD's own loop still derives each cell's
position from the origin plus a per-cell offset (below), matching how
it already worked before this retrofit."
  (multiple-value-bind (x y) (queens-cell-position 0 0 window-width window-height size)
    (values (float x 1.0) (float y 1.0))))

(defun draw-cell-glyph (game x y row col conflicts)
  "The 'miss-placed X' and queen states both need real visual feedback:
a mark shows a plain X, a queen shows the crown glyph — tinted red if
QUEENS-CONFLICTS flags it, so a conflicting placement is genuinely
visible, not just silently non-advancing.

#36's retrofit: both branches previously hand-rolled the identical
'center this glyph within the cell' formula (the same one Wordle's
letter tile also duplicated) — now composes CENTER-WITHIN."
  (ecase (cell-state game row col)
    (:empty nil)
    (:marked
     (let* ((label "X") (font-size 26) (tw (raylib:measure-text label font-size)))
       (multiple-value-bind (tx ty) (edm-engine:center-within (round x) (round y) (round +cell-size+) (round +cell-size+) tw font-size)
         (raylib:draw-text label tx ty font-size (edm-engine:rgb-color (edm-engine:theme-color :muted))))))
    (:queen
     (let* ((font-size 30)
            (tw (edm-engine:glyph-text-width +queen-glyph+ font-size))
            (conflicted (member (cons row col) conflicts :test #'equal)))
       (multiple-value-bind (tx ty) (edm-engine:center-within (round x) (round y) (round +cell-size+) (round +cell-size+) tw font-size)
         (edm-engine:draw-glyph-text +queen-glyph+ tx ty font-size
                                      (if conflicted (edm-engine:rgb-color edm-engine:+color-red+) :black)))))))

;; #37's DEFEFFECT-STATE — Queens' cursor pulse is its own real, named
;; retrofit target (this session's own pulseVal/ese generalization),
;; now declared as data rather than a bare ESE call inline in
;; DRAW-QUEENS-BOARD's own LET* below.
(edm-engine:defeffect-state queens-cursor-pulse (cursor-row cursor-col active-p now)
  (:pulse :key (list :queens-cursor cursor-row cursor-col) :active active-p :now now
          :return :elapsed))

(defun draw-queens-board (game window-width window-height)
  (let* ((board (queens-game-board game))
         (size (queens-board-size board))
         (conflicts (queens-conflicts game))
         (cursor-row (queens-game-cursor-row game))
         (cursor-col (queens-game-cursor-col game))
         ;; ESE tracks time since the cursor most recently entered ITS
         ;; CURRENT CELL, not raw wall-clock, so the pulse starts fresh
         ;; on every cursor move rather than staying phase-locked to
         ;; program start. Computed once per frame (not once per cell)
         ;; with a key encoding the cursor's actual position — calling
         ;; ESE per-cell with one shared key would have every non-
         ;; cursor cell's call clear the cursor cell's own tracked
         ;; state within the same frame, a real bug caught and fixed
         ;; before this landed, not shipped as written first.
         (cursor-elapsed (queens-cursor-pulse cursor-row cursor-col t (raylib:get-time))))
    (multiple-value-bind (ox oy) (queens-grid-origin window-width window-height size)
      (dotimes (row size)
        (dotimes (col size)
          (let* ((x (+ ox (* col (+ +cell-size+ +cell-gap+))))
                 (y (+ oy (* row (+ +cell-size+ +cell-gap+))))
                 (cursor-p (and (= row cursor-row) (= col cursor-col))))
            (draw-cell x y (region-at board row col) size cursor-p (if cursor-p cursor-elapsed 0.0d0))
            (draw-cell-glyph game x y row col conflicts))))
      (raylib:draw-text
       (format nil "Level ~D/~D   Score ~D~A" (queens-game-level game) +queens-level-count+
               (queens-game-score game) (if conflicts "   (conflict!)" ""))
       (round ox) (round (- oy 36)) 22 (edm-engine:rgb-color (edm-engine:theme-color :info))))))

(defmethod edm-engine:game-title ((game queens-game))
  "Queens")

(defvar *theme-sound* nil)

(defun ensure-theme-playing ()
  "#22: non-blocking — see Hearts' identical comment. Polling
IS-SOUND-PLAYING and re-triggering PLAY-SOUND when it's false is
unchanged, still how looping works without raylib's separate Music-
streaming API; only the compute step (once cached, PATTERN-SOUND's own
job before) is now async."
  (unless *theme-sound*
    (setf *theme-sound*
          (edm-engine/audio:ensure-theme-sound-async
           (queens-theme-pattern) +queens-theme-row-duration+
           edm-engine:*engine-bus* :queens-theme :amplitude 0.3)))
  (when (and *theme-sound* (not (raylib:is-sound-playing *theme-sound*)))
    (raylib:play-sound *theme-sound*)))

(defmethod edm-engine:game-update ((game queens-game))
  (ensure-theme-playing)
  (let ((before-row (queens-game-cursor-row game))
        (before-col (queens-game-cursor-col game))
        (before-level (queens-game-level game)))
    (when (raylib:is-key-pressed :key-up) (move-cursor game -1 0))
    (when (raylib:is-key-pressed :key-down) (move-cursor game 1 0))
    (when (raylib:is-key-pressed :key-left) (move-cursor game 0 -1))
    (when (raylib:is-key-pressed :key-right) (move-cursor game 0 1))
    (when (or (/= before-row (queens-game-cursor-row game)) (/= before-col (queens-game-cursor-col game)))
      (edm-engine:bus-push edm-engine:*engine-bus* :audio (list :game :queens :cue :cursor-moved)))
    (when (raylib:is-key-pressed :key-enter)
      (let ((state-before (cell-state game (queens-game-cursor-row game) (queens-game-cursor-col game))))
        (cycle-cell-at-cursor game)
        (cond
          ((> (queens-game-level game) before-level)
           (edm-engine:bus-push edm-engine:*engine-bus* :audio (list :game :queens :cue :level-advanced)))
          ((eq state-before :empty)
           (edm-engine:bus-push edm-engine:*engine-bus* :audio (list :game :queens :cue :cell-marked)))
          ((eq state-before :marked)
           (edm-engine:bus-push edm-engine:*engine-bus* :audio (list :game :queens :cue :queen-placed)))
          (t (edm-engine:bus-push edm-engine:*engine-bus* :audio (list :game :queens :cue :cell-cleared))))))))

(defmethod edm-engine:game-render ((game queens-game) window-width window-height)
  (draw-queens-board game window-width window-height))

(defmethod edm-engine:game-stop-audio ((game queens-game))
  (declare (ignore game))
  (when *theme-sound* (raylib:stop-sound *theme-sound*)))

;; No :RESTORE-FN yet — Queens doesn't support save/load resume in this
;; first playable pass. An honest scope cut, not an oversight: the
;; slot system's contract (GAME-ENTRY-RESTORE-FN nil = "this table
;; doesn't support save/load") already handles it cleanly.
(edm-engine:register-game "Queens" (lambda () (make-queens-game)) :restore-fn #'queens-restore-game)
