{
  "name": "CI",
  "on": {
    "push": {
      "branches": [
        "main"
      ]
    },
    "pull_request": null
  },
  "jobs": {
    "run-tests": {
      "runs-on": "ubuntu-latest",
      "env": {
        "OS": "ubuntu-latest"
      },
      "steps": [
        {
          "name": "Checkout Code",
          "uses": "actions/checkout@v4"
        },
        {
          "name": "Bootstrap and Test",
          "run": "sudo apt-get update -qq\nsudo apt-get install -y -qq sbcl\ncurl -sO https://beta.quicklisp.org/quicklisp.lisp\nsbcl --non-interactive --load quicklisp.lisp \\\n  --eval '(quicklisp-quickstart:install :path (merge-pathnames \"quicklisp/\" (user-homedir-pathname)))'\nsbcl --non-interactive \\\n  --load ~/quicklisp/setup.lisp \\\n  --eval '(push (truename \".\") asdf:*central-registry*)' \\\n  --eval '(ql-dist:install-dist \"http://dist.ultralisp.org/\" :prompt nil)' \\\n  --eval '(ql:quickload :edm-engine/tests/all)' \\\n  --eval '(asdf:test-system :edm-engine/tests/all)'",
          "shell": "bash"
        }
      ]
    }
  }
}